export default [
  {
    smallIconUrl: "",
    detailHintMsg: "",
    itemType: 0,
    image:
      "https://img.alicdn.com/bao/uploaded/i2/192707956/O1CN01PwlNZf28dtf7loeaq_!!192707956.jpg",
    detailUrl: "youxuan://commodity?id=23666008",
    itemFlag: 0,
    saleNum: 482,
    keywords: [],
    originPrice: 33,
    id: 23666008,
    tbOriginPrice: 33,
    commodityId: "605020033180",
    title: "春季减龄三件套韩版针织外套+纯色T恤+百褶裙时尚套装女2020新款",
    taobaoCid: 123216004,
    platform: 1,
    rebateCashAmount: 0,
    largeCoupon: null,
    type: 1,
    couponValue: "",
    expiring: null,
    expireMsg: "",
    price: 32.98,
    isFreePostage: true,
    itemId: 30018657,
    expireDate: null,
    cid: 0,
    url: "https://s.click.taobao.com/p5qRLov",
    isFavorited: false,
    showExpireMsg: false,
    qunTitle: "",
    commodityTypeName: "公用",
    ratingType: "",
    isExpired: false,
    recComment: "",
    select: true,
    selectCount: 1
  },
  {
    smallIconUrl: "",
    detailHintMsg: "",
    itemType: 0,
    image:
      "https://img.alicdn.com/bao/uploaded/i1/2206480155336/O1CN01079RpZ1pHvxgQs6va_!!0-item_pic.jpg",
    detailUrl: "youxuan://commodity?id=22332620",
    itemFlag: 0,
    saleNum: 19146,
    keywords: [],
    originPrice: 99,
    id: 22332620,
    tbOriginPrice: 99,
    commodityId: "601437202802",
    title: "长袖T恤女春秋内搭白色打底衫韩版慵懒风宽松百搭纯色中长款上衣",
    taobaoCid: 50000671,
    platform: 2,
    rebateCashAmount: 0,
    largeCoupon: null,
    type: 1,
    couponValue: "",
    expiring: null,
    expireMsg: "",
    price: 9.9,
    isFreePostage: true,
    itemId: 28705505,
    expireDate: null,
    cid: 0,
    url: "https://s.click.taobao.com/TYjRLov",
    isFavorited: false,
    showExpireMsg: false,
    qunTitle: "",
    commodityTypeName: "熊猫",
    ratingType: "",
    isExpired: false,
    recComment: "",
    select: true,
    selectCount: 1
  },
  {
    smallIconUrl: "",
    detailHintMsg: "",
    itemType: 0,
    image:
      "https://img.alicdn.com/i4/2019221222/O1CN011KtiSNCV4VvP5ST_!!2019221222.jpg",
    detailUrl: "youxuan://commodity?id=27887217",
    itemFlag: 0,
    saleNum: 42,
    keywords: [],
    originPrice: 458,
    id: 27887217,
    tbOriginPrice: 458,
    commodityId: "559982693459",
    title: "棉衣女外套2019新款冬季韩版中长款过膝加厚面包羽绒棉服学生棉袄",
    taobaoCid: 50008900,
    platform: 2,
    rebateCashAmount: 0,
    largeCoupon: null,
    type: 1,
    couponValue: "",
    expiring: null,
    expireMsg: "",
    price: 69.9,
    isFreePostage: true,
    itemId: 9041200,
    expireDate: null,
    cid: 0,
    url: "https://s.click.taobao.com/M1QTLov",
    isFavorited: false,
    showExpireMsg: false,
    qunTitle: "",
    commodityTypeName: "公用",
    ratingType: "",
    isExpired: false,
    recComment: "",
    select: true,
    selectCount: 1
  },
  {
    smallIconUrl: "",
    detailHintMsg: "",
    itemType: 0,
    image:
      "https://img.alicdn.com/bao/uploaded/i4/3543552751/TB2l0aHIYSYBuNjSspiXXXNzpXa_!!3543552751-0-item_pic.jpg",
    detailUrl: "youxuan://commodity?id=3830226",
    itemFlag: 0,
    saleNum: 97,
    keywords: [],
    originPrice: 19.9,
    id: 3830226,
    tbOriginPrice: 19.9,
    commodityId: "574682180196",
    title: "2020早春季内搭欧美打底小衫女ins欧货欧洲站上衣洋气秋长袖t恤潮",
    taobaoCid: 50000671,
    platform: 2,
    rebateCashAmount: 0,
    largeCoupon: null,
    type: 1,
    couponValue: "",
    expiring: null,
    expireMsg: "",
    price: 9.95,
    isFreePostage: true,
    itemId: 10286089,
    expireDate: null,
    cid: 0,
    url: "https://s.click.taobao.com/RvNSLov",
    isFavorited: false,
    showExpireMsg: false,
    qunTitle: "【加厚上衣】2018新款秋冬 · 袖t恤",
    commodityTypeName: "熊猫",
    ratingType: "",
    isExpired: false,
    recComment: "超百搭打底，怎么搭配都好看",
    select: true,
    selectCount: 1
  },
  {
    smallIconUrl: "",
    detailHintMsg: "",
    itemType: 0,
    image:
      "https://img.alicdn.com/bao/uploaded/i2/508747471/O1CN01ipsxqf253lUgNu1zP_!!508747471.jpg",
    detailUrl: "youxuan://commodity?id=22670176",
    itemFlag: 0,
    saleNum: 36,
    keywords: [],
    originPrice: 399,
    id: 22670176,
    tbOriginPrice: 399,
    commodityId: "602147546538",
    title: "棉服女ins港风原宿宽松棉衣冬季中长款棉袄过膝羊羔毛工装外套女",
    taobaoCid: 50008900,
    platform: 1,
    rebateCashAmount: 0,
    largeCoupon: null,
    type: 1,
    couponValue: "",
    expiring: null,
    expireMsg: "",
    price: 198,
    isFreePostage: true,
    itemId: 29035159,
    expireDate: null,
    cid: 0,
    url: "https://s.click.taobao.com/JGwRLov",
    isFavorited: false,
    showExpireMsg: false,
    qunTitle: "",
    commodityTypeName: "熊猫",
    ratingType: "",
    isExpired: false,
    recComment: "",
    select: true,
    selectCount: 1
  }
];
      